# Generated by Django 5.0.4 on 2024-04-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewNotes',
        ),
    ]
